spring.application.name=PROYECTO_DBP
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL}
jwt.secret=${JWT_SECRET}
jwt.expiration.access=${JWT_EXPIRATION_ACCESS}
jwt.expiration.refresh=${JWT_EXPIRATION_REFRESH}